import type { Metadata } from "next";
import { Database, EyeOff, FileClock, KeyRound, LockKeyhole, ServerCrash, ShieldCheck, UserCheck } from "lucide-react";

import { MarketingFooter, MarketingHeader } from "@/components/marketing-shell";

export const metadata: Metadata = { title: "Security", description: "OrthoCode AI's current development-stage privacy, safety, and review controls." };

const controls = [
  [EyeOff, "De-identified development", "Development uploads require an explicit de-identification confirmation. Production use with PHI is not represented as ready."],
  [LockKeyhole, "No silent coding fallback", "A JEV timeout, provider error or malformed response forces a RED review result without fabricated coding lines."],
  [Database, "Licensed source isolation", "Raw licensed codebook files remain outside the runtime API and frontend; runtime lookup uses normalized published releases."],
  [KeyRound, "Secrets stay server-side", "The frontend receives no model-provider secrets or raw reference files. Provider permissions are explicit configuration."],
  [FileClock, "Append-only review trail", "Human corrections are added to the audit record without rewriting the original model output."],
  [UserCheck, "Autonomy guarded", "Autonomous coding is disabled by default and remains gated by engine mode, successful execution, thresholds and rule results."],
] as const;

export default function SecurityPage() {
  return <div className="min-h-screen bg-white text-ink"><MarketingHeader /><main><section className="bg-marketing px-5 pb-20 pt-16 text-white sm:px-8 sm:pb-24 sm:pt-20 lg:px-12"><div className="mx-auto max-w-5xl"><div className="marketing-kicker"><span /> Security and privacy</div><h1 className="mt-7 max-w-4xl text-5xl font-semibold leading-[1.02] tracking-[-0.05em] sm:text-7xl">Trust starts with stating the boundary honestly.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-300">OrthoCode AI is a development-stage system for de-identified charts. These are the safeguards implemented today—and the production work that remains.</p></div></section><section className="bg-warm px-5 py-20 sm:px-8 sm:py-28 lg:px-12"><div className="mx-auto max-w-6xl"><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{controls.map(([Icon, title, body]) => <article key={title} className="rounded-2xl border border-line bg-white p-7"><div className="grid h-11 w-11 place-items-center rounded-xl bg-emerald-50 text-teal"><Icon size={20} /></div><h2 className="mt-6 text-lg font-semibold tracking-[-0.02em]">{title}</h2><p className="mt-3 text-sm leading-7 text-slate">{body}</p></article>)}</div></div></section><section className="bg-white px-5 py-20 sm:px-8 sm:py-24 lg:px-12"><div className="mx-auto grid max-w-5xl gap-10 lg:grid-cols-[0.75fr_1.25fr]"><div><div className="section-kicker">Before production</div><h2 className="marketing-h2 mt-5">Controls still requiring formal review.</h2></div><div className="rounded-2xl border border-amber-200 bg-amber-50 p-7"><div className="flex items-center gap-3 text-amber-900"><ServerCrash size={20} /><h3 className="font-semibold">Production readiness is not implied</h3></div><p className="mt-4 text-sm leading-7 text-amber-900">Production deployment still requires a compliance review, appropriate vendor agreements, approved private object storage, authentication and role-based access, key rotation, retention enforcement and audit monitoring.</p></div></div></section><section className="bg-warm px-5 py-16 sm:px-8 lg:px-12"><div className="mx-auto flex max-w-5xl items-start gap-4 rounded-2xl bg-navy p-7 text-white"><ShieldCheck className="mt-1 shrink-0 text-cyan-300" /><div><h2 className="text-lg font-semibold">Current posture in one sentence</h2><p className="mt-2 text-sm leading-7 text-slate-300">Bounded de-identified inputs, no silent fallback, deterministic hard rules, mandatory human review, and an append-only correction trail.</p></div></div></section></main><MarketingFooter /></div>;
}
