"use client";

import { ArrowRight, CheckCircle2 } from "lucide-react";
import { FormEvent, useState } from "react";

export function AccessForm() {
  const [submitted, setSubmitted] = useState(false);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSubmitted(true); }
  if (submitted) return <section className="rounded-3xl border border-emerald-200 bg-white p-8 shadow-panel sm:p-10" aria-live="polite"><CheckCircle2 size={28} className="text-teal" /><h2 className="mt-6 text-2xl font-semibold tracking-[-0.03em]">Request captured in this preview.</h2><p className="mt-3 text-sm leading-7 text-slate">The lead endpoint is intentionally not connected yet. Your information was not transmitted. Connect this form to an approved CRM or email workflow before launch.</p></section>;
  return <form onSubmit={submit} className="rounded-3xl border border-line bg-white p-7 shadow-panel sm:p-10"><div className="grid gap-5 sm:grid-cols-2"><label><span className="form-label">First name</span><input required autoComplete="given-name" /></label><label><span className="form-label">Last name</span><input required autoComplete="family-name" /></label></div><label className="mt-5 block"><span className="form-label">Work email</span><input required type="email" autoComplete="email" /></label><label className="mt-5 block"><span className="form-label">Organization</span><input required autoComplete="organization" /></label><label className="mt-5 block"><span className="form-label">Your role</span><select required defaultValue=""><option disabled value="">Select a role</option><option>Coding leader</option><option>Credentialed coder</option><option>Revenue-cycle leader</option><option>Clinical or compliance leader</option><option>Technology partner</option></select></label><label className="mt-5 block"><span className="form-label">What should we understand about your workflow?</span><textarea rows={4} placeholder="Optional" /></label><p className="mt-5 text-xs leading-5 text-slate">Preview only: this form is not connected to a backend yet and does not transmit data.</p><button className="button-primary mt-6 w-full" type="submit">Request access <ArrowRight size={16} /></button></form>;
}
