"use client";

import { LoaderCircle, Search } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";

import { Alert, Empty, messageOf, PanelHeading } from "@/components/ui";
import { CodeEntry, ModifierEntry, searchCodes, searchModifiers } from "@/lib/api";

export default function CodebookPage() {
  const [mode, setMode] = useState<"codes" | "modifiers">("codes");
  const [query, setQuery] = useState("29827");
  const [system, setSystem] = useState("CPT");
  const [codes, setCodes] = useState<CodeEntry[]>([]);
  const [modifiers, setModifiers] = useState<ModifierEntry[]>([]);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { void searchCodes("29827", "CPT").then(setCodes).catch((caught) => setError(messageOf(caught))); }, []);
  async function runSearch(event?: FormEvent) { event?.preventDefault(); if (!query.trim()) return; setBusy(true); setError(null); try { if (mode === "codes") setCodes(await searchCodes(query, system || undefined)); else setModifiers(await searchModifiers(query)); } catch (caught) { setError(messageOf(caught)); } finally { setBusy(false); } }
  function switchMode(next: "codes" | "modifiers") { setMode(next); setQuery(next === "codes" ? "29827" : "59"); setError(null); if (next === "codes" && !codes.length) void searchCodes("29827", "CPT").then(setCodes).catch((caught) => setError(messageOf(caught))); if (next === "modifiers" && !modifiers.length) void searchModifiers("59").then(setModifiers).catch((caught) => setError(messageOf(caught))); }
  const count = mode === "codes" ? codes.length : modifiers.length;
  return <div className="space-y-5">{error && <Alert tone="bad" onClose={() => setError(null)}>{error}</Alert>}<section className="panel"><PanelHeading title="Published codebook" body="Search active code and modifier records" /><div className="p-5"><div className="mb-4 flex gap-2" role="tablist" aria-label="Codebook search mode"><button role="tab" aria-selected={mode === "codes"} className={mode === "codes" ? "button-primary" : "button-secondary"} onClick={() => switchMode("codes")}>Codes</button><button role="tab" aria-selected={mode === "modifiers"} className={mode === "modifiers" ? "button-primary" : "button-secondary"} onClick={() => switchMode("modifiers")}>Modifiers</button></div><form className="flex flex-col gap-3 sm:flex-row" onSubmit={runSearch}>{mode === "codes" && <select className="control sm:w-44" value={system} onChange={(event) => setSystem(event.target.value)}><option value="CPT">CPT</option><option value="HCPCS">HCPCS</option><option value="ICD10CM">ICD-10-CM</option><option value="">All systems</option></select>}<div className="search-box flex-1"><Search size={15} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={mode === "codes" ? "Code or description" : "Modifier or description"} /></div><button className="button-primary" disabled={busy || !query.trim()}>{busy ? <LoaderCircle className="animate-spin" size={15} /> : <Search size={15} />}Search</button></form></div></section><section className="panel overflow-hidden"><PanelHeading title={mode === "codes" ? "Code results" : "Modifier results"} body={`${count} active records`} />{count === 0 ? <Empty title="No matching records" body="Try a broader code, description, or modifier search." /> : mode === "codes" ? <CodeResults items={codes} /> : <ModifierResults items={modifiers} />}</section></div>;
}

function CodeResults({ items }: { items: CodeEntry[] }) { return <><div className="hidden overflow-x-auto md:block"><table><thead><tr><th>System</th><th>Code</th><th>Description</th><th>Category</th><th>Effective</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td>{item.code_system}</td><td className="font-mono text-base font-semibold text-ink">{item.code}</td><td><div className="max-w-2xl whitespace-normal">{item.long_description || item.short_description || "—"}</div></td><td>{item.category || item.chapter || "—"}</td><td>{item.effective_from || "—"}</td></tr>)}</tbody></table></div><div className="divide-y divide-line md:hidden">{items.map((item) => <article className="p-4" key={item.id}><div className="flex items-center gap-2"><span className="code-system">{item.code_system}</span><span className="font-mono text-lg font-semibold">{item.code}</span></div><p className="mt-3 text-sm leading-6 text-slate">{item.long_description || item.short_description || "No description"}</p><p className="mt-2 text-xs text-slate">{item.category || item.chapter || "Uncategorized"} · {item.effective_from || "No effective date"}</p></article>)}</div></>; }
function ModifierResults({ items }: { items: ModifierEntry[] }) { return <><div className="hidden overflow-x-auto md:block"><table><thead><tr><th>Modifier</th><th>Description</th><th>Type</th><th>Effective</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td className="font-mono text-base font-semibold text-ink">−{item.modifier}</td><td><div className="max-w-2xl whitespace-normal">{item.description || "—"}</div></td><td>{item.type.replaceAll("_", " ")}</td><td>{item.effective_from || "—"}</td></tr>)}</tbody></table></div><div className="divide-y divide-line md:hidden">{items.map((item) => <article className="p-4" key={item.id}><div className="font-mono text-lg font-semibold">−{item.modifier}</div><p className="mt-3 text-sm leading-6 text-slate">{item.description || "No description"}</p><p className="mt-2 text-xs capitalize text-slate">{item.type.replaceAll("_", " ")} · {item.effective_from || "No effective date"}</p></article>)}</div></>; }
