"use client";

import { Activity, Archive, CircleAlert, Database, LoaderCircle, RefreshCw, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";

import { Alert, Empty, LoadingPanel, messageOf, number, PanelHeading } from "@/components/ui";
import { getOverview, Overview, publishRelease, startImport } from "@/lib/api";

export default function ReferencePage() {
  const [overview, setOverview] = useState<Overview | null>(null);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const load = async () => { setOverview(await getOverview()); setLoading(false); };
  useEffect(() => { void load().catch((caught) => { setError(messageOf(caught)); setLoading(false); }); }, []);
  async function action(name: string, task: () => Promise<unknown>, success: string) { setBusy(name); setError(null); try { await task(); await load(); setNotice(success); } catch (caught) { setError(messageOf(caught)); } finally { setBusy(null); } }
  if (loading) return <LoadingPanel label="Loading reference controls" />;
  if (!overview) return <div className="panel"><Empty title="Reference service unavailable" body="Start the API and verify the admin reference endpoint to inspect releases." /></div>;
  const records = Object.values(overview.record_counts).reduce((sum, value) => sum + value, 0);
  return <div className="space-y-5">{notice && <Alert tone="good" onClose={() => setNotice(null)}>{notice}</Alert>}{error && <Alert tone="bad" onClose={() => setError(null)}>{error}</Alert>}<section className={`gate-card ${overview.gate === "ready" ? "gate-ready" : "gate-blocked"}`}><div className="flex gap-4"><div className={`gate-icon ${overview.gate === "ready" ? "surface-good text-teal" : "surface-warning text-amber"}`}>{overview.gate === "ready" ? <Database size={23} /> : <CircleAlert size={23} />}</div><div><h2 className="text-lg font-semibold">{overview.gate === "ready" ? "Published codebook is runtime-ready" : "Coding gate is blocked"}</h2><p className="mt-2 text-sm text-slate">{number.format(overview.licensed_cpt_records)} licensed CPT codes · {overview.active_release?.name ?? "no active release"}</p></div></div><div className="flex gap-2"><button className="button-secondary" disabled={busy !== null} onClick={() => void action("import", startImport, "Reference normalization queued.")}>{busy === "import" ? <LoaderCircle className="animate-spin" size={15} /> : <RefreshCw size={15} />}Normalize</button><button className="button-primary" disabled={busy !== null || overview.latest_release?.status !== "validated"} onClick={() => overview.latest_release && void action("publish", () => publishRelease(overview.latest_release!.id), "Reference release published.")}>{busy === "publish" && <LoaderCircle className="animate-spin" size={15} />}Publish</button></div></section><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><ReferenceMetric icon={Database} label="Licensed CPT" value={number.format(overview.licensed_cpt_records)} detail="Active codes" tone="good" /><ReferenceMetric icon={Archive} label="Source files" value={number.format(overview.source_inventory.files_discovered)} detail="Checksummed artifacts" /><ReferenceMetric icon={Activity} label="Runtime records" value={number.format(records)} detail={overview.ncci_runtime.mode.replaceAll("_", " ")} /><ReferenceMetric icon={ShieldCheck} label="Autonomy" value={overview.autonomous_coding_enabled ? "Enabled" : "Disabled"} detail="Empirical gate required" tone={overview.autonomous_coding_enabled ? "warning" : "good"} /></section><section className="panel overflow-hidden"><PanelHeading title="Runtime reference coverage" body="Normalized tables and indexed licensed source data" /><div className="grid sm:grid-cols-2 lg:grid-cols-4">{Object.entries(overview.record_counts).map(([key, value]) => <div key={key} className="border-b border-r border-line p-5"><div className="font-mono text-xl font-semibold">{number.format(value)}</div><div className="mt-1 text-xs font-medium capitalize text-slate">{key.replaceAll("_", " ")}</div></div>)}</div></section><Alert tone="warning">System administration area. Publishing a release changes which licensed records can be used for new coding runs.</Alert></div>;
}

function ReferenceMetric({ icon: Icon, label, value, detail, tone = "neutral" }: { icon: typeof Database; label: string; value: string; detail: string; tone?: "good" | "warning" | "neutral" }) { return <div className="panel flex items-start gap-4 p-5"><div className={`metric-icon ${tone === "good" ? "surface-good text-teal" : tone === "warning" ? "surface-warning text-amber" : "surface-neutral text-blue"}`}><Icon size={18} /></div><div><div className="text-xs font-semibold text-slate">{label}</div><div className="mt-1 text-2xl font-semibold tracking-[-0.04em]">{value}</div><div className="mt-1 text-xs capitalize text-slate">{detail}</div></div></div>; }
